### ISSUE TITLE
Pluralsight udpated its player framework today, the extension does not work, would it be possible to also update it? Very much appreciated.

### ISSUE THREAD

**Issue by sclihua** [sahilsehwag/pluralsight-downloader-chrome-extension#67] opened 2023-11-07 19:27 UTC
Nothing works, tried the shortcut and clicked buttons, not work for me. It will be highly appreciated if the extension can be updated. Thanks a lot.

**Comment by sahilsehwag** [comment] 2023-11-07 19:59
@sclihua 

- I am working on a really cool complete rewrite of the project. 
- Building it from scratch, it will take a bit longer for it to be available for everyone
- As for player framework being updated, I checked all the things that should make this work are as it is and in place, so everything should work as it was working before
- As for keyboard shortcuts, keyboard shortcuts was removed in favour of popup, which is easier for everyone to use
- Can you share how you installed and setup everything?
- What are the errors you are getting in extension tab inside devtools?

**Comment by sclihua** [comment] 2023-11-07 20:35
Thanks a lot for replying to me. @sahilsehwag 

Very good to know you are working on a wonderful new version, look forward to it.

To your questions:
I installed the extension by loading the unpacked, and then just tried the way referred to, by changing the crx and drg-n-drop. Both did not work. By the way, the extension was working this morning, and then Pluralsight changed the player. Now the link becomes https://app.pluralsight.com/ilx/video-courses/clips/bb88f8f1-42e3-4656-9e53-75edf9c4db6d when the course is playing.

F12 dev tools gave error like this:
Keypress: 86
script.js:123 [PluralsightCourseDownloader]:[STATUS]: Downloading course from now on ...
script.js:123 [PluralsightCourseDownloader]:[STATUS]: Fetching course information...
bb88f8f1-42e3-4656-9e53-75edf9c4db6d:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLDocument.<anonymous> (script.js:738:28)
    at HTMLDocument.dispatch (jquery.slim.min.js:2:41964)
    at v.handle (jquery.slim.min.js:2:39983)
    at Object.trigger (jquery.slim.min.js:2:62230)
    at HTMLDocument.<anonymous> (jquery.slim.min.js:2:62825)
    at Function.each (jquery.slim.min.js:2:2765)
    at w.fn.init.each (jquery.slim.min.js:2:1438)
    at w.fn.init.trigger (jquery.slim.min.js:2:62801)
    at script.js:669:15

Thanks.

**Comment by sahilsehwag** [comment] 2023-11-07 20:45
@sclihua 

- Seems like they are AB testing this, since I am getting the old player
- But I am able to access the new player, using the link you provided
- I can see that this will definitely fail and changes will be required to add support for getting course TOC in this new flow
- If you or someone is interested in fixing this, they can submit the PR to add support for the new flow as well.
- As for me, I'll add the support in the newer version that I am building from scratch
- As of now, I am not sure, when will this new version will be finished or at least publishable

**Comment by sclihua** [comment] 2023-11-07 20:58
@sahilsehwag 

I tried the old URL, it automatically navigates to the newer one. It seems the new player is enforced in my area.
Then do not bother with it, I can live with the online version and wait for your next update.

Thanks.

**Comment by sahilsehwag** [comment] 2023-11-07 21:16
@sclihua 

- 1 last thing you can try is VPN to access a different region.
- I am operating from India, maybe you can try Asian regions

**Comment by puyaalexxx** [comment] 2023-11-11 09:02
the same issue happens to me

**Comment by siwanian** [comment] 2023-11-13 21:56
Same issue with me too. Nothing is working :(

**Comment by siwanian** [comment] 2023-11-13 21:58
link looks like below now. They have added ilx

https://app.pluralsight.com/ilx/video-courses/c39de8aa-6e83-4103-95c2-70d237450a72/4057669d-edcf-4c63-a7e5-3c51ca484cf1/ab9ff106-c813-4a3d-9f5f-31ffa4e88e08

**Comment by siwanian** [comment] 2023-11-21 00:40
@sahilsehwag let me know if you need any help in fixing this extension??

**Comment by SagarS456** [comment] 2023-11-23 16:52
Pluralsight has 2 differnet layout in one layout inside window.__Next_DATA__    "tableofcontents" data is present and in other layout window.__Next_DATA__   is blank. The code is in script.js file line no 738

**Comment by 6ebeng** [comment] 2023-11-24 11:55
The extention is dead

**Comment by 6ebeng** [comment] 2023-11-29 17:50
@sahilsehwag need your approval pulI request I updated some code and then it works!

**Comment by mnaeem600** [comment] 2023-12-28 12:13
@sahilsehwag
How much of an effort it is to fix the curret extension to look at new TOC? I can try to have a look if you can give me some pointer on where to correct this issue.

Thanks

**Comment by 6ebeng** [comment] 2023-12-28 12:19
Already fixed, it need approve my pull request.

**Comment by mnaeem600** [comment] 2023-12-28 13:31
@6ebeng beng
Where to find the fixed version?
Thanks

**Comment by 6ebeng** [comment] 2023-12-28 14:09
check this out [https://github.com/6ebeng/pluralsight-downloader-chrome-extension-plus](https://github.com/6ebeng/pluralsight-downloader-chrome-extension-plus)

**Comment by mnaeem600** [comment] 2023-12-28 14:19
Hi Tishko,
It does not work. The url in web browser is

https://app.pluralsight.com/ilx/video-courses/

Where does the changes need to be made in script.js?



Thanks

**Comment by siwanian** [comment] 2024-01-04 18:59
https://github.com/6ebeng/pluralsight-downloader-chrome-extension-plus 

gives 404 error :(

**Comment by siwanian** [comment] 2024-01-23 05:27
@6ebeng any idea how to download your extension?? it shows 404 error :(

**Comment by mnaeem600** [comment] 2024-01-23 12:39
Hi siwanian,
It works. I got a copy. Send me your PM.


Thanks

**Comment by sclihua** [comment] 2024-01-23 21:40
@mnaeem600 or @6ebeng, do you mind also forwarding me a copy, to: sclihua@gmail.com? Thanks.

**Comment by g-h-mac** [comment] 2024-01-31 18:27
@mnaeem600 
> Hi siwanian, It works. I got a copy.
Can you please share the working version?

**Comment by sahilsehwag** [comment] 2024-02-01 22:06
@6ebeng @mnaeem600 
- If you guys can provide the PR I will merge it into the master branch, that should suffice until I finish up the rewrite
- I have suggested some changes in the PR by @6ebeng (https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/pull/69#issuecomment-1922337105)

**Comment by g-h-mac** [comment] 2024-02-03 01:12
@dmitry-donskoy @mnaeem600 : Following the link @sahilsehwag provided, I see that 6ebeng deleted his patch-1 branch 3 months ago. But if you click on the "Files Changed" tab, it appears his partially completed work still exists as a diff: https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/pull/69/files

**Comment by Caroga** [comment] 2024-02-06 16:30
Hi there! I am excited about this rewrite and am looking forward to being able to use this extensions.
Is there anything you need help with at the moment?

**Comment by g-h-mac** [comment] 2024-02-09 22:29
@Caroga

>Is there anything you need help with at the moment?

Yes. Please look at the PR at https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/pull/69#issuecomment-1922337105 and you will see that @darjimahesh commented there recently that the proposed changes make the extension into a working product. I know this is a deleted PR as 6ebeng deleted his work from his github account (404), but the proposed changes are still visible at https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/pull/69/files 

Please apply these changes to a copy of master, test it, and if you agree it is working, please make a new PR that sahilsehwag can merge into master.

Thanks for your interest in helping.

**Comment by Caroga** [comment] 2024-02-15 21:32
I can confirm that the files are being downloaded.
The extensions has downloaded 4 videos, after which it stopped. The timeout (waiting xx:xx) time stopped counting down.
After restarting the browser I found the following error in my developers console when retrying:
![image](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/assets/4005934/54e4a93e-ed65-467d-8cdb-7693fbf41ec5)

**Comment by tanushshukla** [comment] 2024-02-20 09:18
I think I've managed to fix the issue. What course are you trying? I can test and create a PR.

I'm just doing more testing right now.

**Comment by dmitry-donskoy** [comment] 2024-02-20 14:42
> I think I've managed to fix the issue. What course are you trying? I can test and create a PR.
> 
> I'm just doing more testing right now.

If you can, please, download this course !

**Comment by Caroga** [comment] 2024-02-20 17:45
@tanushshukla I was downloading a course on kubernetes but the mentioned course above is as good as any. 
I find it weird that the download was working but broke later on. I thought maybe a anti-download mechanism was triggered on pluralsight. Were you able to download an entire course?

**Comment by tanushshukla** [comment] 2024-02-20 18:21
> > I think I've managed to fix the issue. What course are you trying? I can test and create a PR.
> > I'm just doing more testing right now.
> 
> If you can, please, download this course ! https://app.pluralsight.com/library/courses/spring-framework-6-building-java-web-applications/table-of-contents

I had to make a small adjustment but its working fine now.

> @tanushshukla I was downloading a course on kubernetes but the mentioned course above is as good as any. I find it weird that the download was working but broke later on. I thought maybe a anti-download mechanism was triggered on pluralsight. Were you able to download an entire course?
Yes, its weird that it stopped mid way. That did not happen to me. 
The courseId and courseURL is different based on new and old URL. 

I can test with the specific course if you can give me and test it.

Will raise a PR soon.

**Comment by 6ebeng** [comment] 2024-02-20 19:22
be patient I'm about to build something different :)

![image](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/assets/90611955/7fac5fee-47fa-484f-a9d6-2a1356a4ccfe)

![image](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/assets/90611955/19b0f50c-8d53-4bf1-b091-18a7e34fd6ef)

**Comment by tanushshukla** [comment] 2024-02-20 22:36
> be patient I'm about to build something different :)
> 
> ![image](https://private-user-images.githubusercontent.com/90611955/306390322-7fac5fee-47fa-484f-a9d6-2a1356a4ccfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Njg4ODQsIm5iZiI6MTcwODQ2ODU4NCwicGF0aCI6Ii85MDYxMTk1NS8zMDYzOTAzMjItN2ZhYzVmZWUtNDdmYS00ODRmLWE5ZDYtMmExMzU2YTRjY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIyMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZWVmYTc1MmVmZjUwN2FjYmRiZDQzZGM5ZTY5MTMyZWZlNDE3MjMzZmQ1Yzg2MWJlNWE2NWY0ZmM5M2FjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpxaD519FfkvqKNpRQ0ky5ZqoCijhMwziL2mw0sUhlI)
> 
> ![image](https://private-user-images.githubusercontent.com/90611955/306390560-19b0f50c-8d53-4bf1-b091-18a7e34fd6ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Njg4ODQsIm5iZiI6MTcwODQ2ODU4NCwicGF0aCI6Ii85MDYxMTk1NS8zMDYzOTA1NjAtMTliMGY1MGMtOGQ1My00YmYxLWIwOTEtMThhN2UzNGZkNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIyMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTEwMTRlM2I3YmUxMjliYzE4NGQ1ZmY3NGY5ZTBmZWNkM2Q2ZDVmYjAwMjhiNjJjMTkxNWJkMjM0MzljODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.leL5OTzmg0qoor7Ikvy19Ph9KQ56Ev-S2KX_SFMT-QE)

that looks really sick!

**Comment by tanushshukla** [comment] 2024-02-21 17:46
> This is the course I was trying to download. I was able to get the second section, chapter 3 (03. Introducing the Kubernetes API - Objects and API Server). I was getting errors with chapter 4.

It downloaded the whole course. Will raise the PR tonight.

**Comment by tanushshukla** [comment] 2024-02-21 21:55
https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/pull/73
Raised the PR here.

**Comment by BuldoZZer85** [comment] 2024-02-22 10:33
> #73 Raised the PR here.

With the PR extension had started to work. Already downloaded 3 courses and 1 is on the way.

Thanks community!

**Comment by BuldoZZer85** [comment] 2024-02-24 10:50
On my experience the extension sometimes didn't work on a browser like Vivaldi. I didn't find the reason because it started work on new Brave brower after reinstalling the extension.

**Comment by sahilsehwag** [comment] 2024-02-27 22:21
Merged #73 by @tanushshukla. This should be working now. Closing this issue for now.

**Closed by sahilsehwag** 2024-02-27 22:21 UTC

**Comment by 5aj031** [comment] 2024-04-01 00:53
@sahilsehwag  @tanushshukla am I missing something or this last merge doest solve the issue? 
I'm trying to download the following course, but it is not working :/ 

https://app.pluralsight.com/ilx/aws-certified-cloud-practitioner-(clf-c02)-cloud-foundations-and-compute/4c287c6d-13d9-40cf-a98e-526acb973aa2/5069ba76-92ed-413c-8570-b69084560410

**Comment by g-h-mac** [comment] 2024-04-11 21:00
@5aj031 @sahilsehwag  @tanushshukla I find the extension broken today. Trying to download a course using Chrome and this extension and when it goes to download a video it tries to download some xml file  and not an mp4. The result is "Failed no file"
