### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by MrTimonM** [sahilsehwag/pluralsight-downloader-chrome-extension#71] opened 2024-01-10 11:14 UTC
I was trying to download a video using this extension and It's not downloading anything. 
I am getting erros. 

> VM110:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at HTMLDocument.<anonymous> (script.js:738:28)
>     at HTMLDocument.dispatch (jquery.slim.min.js:2:41964)
>     at v.handle (jquery.slim.min.js:2:39983)
>     at Object.trigger (jquery.slim.min.js:2:62230)
>     at HTMLDocument.<anonymous> (jquery.slim.min.js:2:62825)
>     at Function.each (jquery.slim.min.js:2:2765)
>     at w.fn.init.each (jquery.slim.min.js:2:1438)
>     at w.fn.init.trigger (jquery.slim.min.js:2:62801)
>     at script.js:669:15

Please let me know if there is a solution for this and if there will be updates of this extension.
Thank you.

**Comment by sahilsehwag** [comment] 2024-02-27 22:19
Duplicate of #67

**Closed by sahilsehwag** 2024-02-27 22:19 UTC
