### ISSUE TITLE
Files are downloading with trimmed File Names.

### ISSUE THREAD

**Issue by IssacEinstein** [sahilsehwag/pluralsight-downloader-chrome-extension#24] opened 2021-04-29 09:47 UTC
Files are downloading with trimmed File Names.
But, ".m3u" contains the FileList with Full Names.

**Comment by JKamsker** [comment] 2021-04-29 21:21
What course are you downloading?

**Comment by IssacEinstein** [comment] 2021-04-30 03:41
> What course are you downloading?

It applies to Any Pluralsight Course which contains lengthy File Names.

**Comment by alextnull** [comment] 2021-06-26 10:11
> Files are downloading with trimmed File Names.
> But, ".m3u" contains the FileList with Full Names.

Facing the same problem, I figured out the possible reason for this behavior.
This is most likely due to the limitation of the maximum path length in Windows, which is defined as 260 characters.
This problem can be solved in several ways: 
1) Download files to the root of the disk.
2) Enable Long Paths in Windows 10, Version 1607, and Later.
3) Use symbolic links.
4) Use the 'subst' command to mount the folder as a disk.
5) There are probably other ways to do that.

**Comment by IssacEinstein** [comment] 2021-07-08 18:55
> > Files are downloading with trimmed File Names.
> > But, ".m3u" contains the FileList with Full Names.
> 
> Facing the same problem, I figured out the possible reason for this behavior.
> This is most likely due to the limitation of the maximum path length in Windows, which is defined as 260 characters.
> This problem can be solved in several ways:
> 
> 1. Download files to the root of the disk.
> 2. Enable Long Paths in Windows 10, Version 1607, and Later.
> 3. Use symbolic links.
> 4. Use the 'subst' command to mount the folder as a disk.
> 5. There are probably other ways to do that.

I tried using registry edit in windows 10 v21H1... But still failing to get the file name.

**Comment by sahilsehwag** [comment] 2021-07-11 08:56
@IssacEinstein 
This looks like a OS limitation, Closing the issue since this is not a bug in the extension. 

Do let us know if there are some updates on this issue, since this might help other people too

**Closed by sahilsehwag** 2021-07-11 08:56 UTC
